# NumPy

 <img src="https://numpy.org/images/logos/numpy.svg" alt="NumPy" width="100px" /><br>

The fundamental package for scientific computing with Python. Use for basic data representation and linear algebra operation. NumPy also provide several data formats and array format for python. The data manipulation and data preprocessing also can be done with NumPy. From Aj.Ple experience, Aj.Ple suggest to change data representation to NumPy for Data Engineering & Data Analytics work. <br>

P.S. Linear Algebra is about linear equation in form of vector and matrix !!

www.numpy.org

### 1. NumPy Array

To use external Library in PyThon, we will use the command called <i>import</i>.<br> In this example, we use external library called <i>NumPy</i> and give it a short name as <i>np</i>. 

In [3]:
import numpy as np

กด tap เพื่อดูคำสั่ง ของ numpy เช่น np. * กด tap * 

!pip install ชื่อชุดคำสั่ง เช่น !pip install numpy

In [12]:
!pip install numpy

คือคำสั่งทำให้installชุดคำสั่งที่เราไม่มี

In [11]:
np.__version__    #คำสั่งดูversion

'1.19.5'

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) # .array เป็นชุดคำสั่งในnumpy 
a # array 1 มิติ / vector / 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array 1 มิติ / vector / 1D array

In [16]:
L = [1,2,3,4,5,6,7,8,9,10]
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
bb = np.array([[1,2,3],[4,5,6],[7,8,9]]) #Matrix / 2D array
bb

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[0]

1

In [15]:
a[2:5] #ช่วยได้เยอะมาก สะดวก

array([3, 4, 5])

In [17]:
L[2:5]

[3, 4, 5]

In [18]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [19]:
L[:6]

[1, 2, 3, 4, 5, 6]

In [20]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [22]:
a[-1] #จากตัวสุดท้ายเข้ามา1

10

In [24]:
a[-2]

9

In [26]:
a[2:-3] #ข้างหน้ามา2ข้างหลังมา3

array([3, 4, 5, 6, 7])

In [27]:
a[-5:] #ถอยมา5ตัวแล้ว เริ่มไปสุด

array([ 6,  7,  8,  9, 10])

In [ ]:
a[-5:-1]

In [28]:
np.size(a) #เช็คขนาดarray

10

In [29]:
np.shape(a) #เช็คเป็นarrayกี่มิติ มีกี่แถวกี่คอลลัม

(10,)

In [30]:
np.shape(bb)

(3, 3)

-----------------------------------------

In [41]:
a[a[2]] # a[3] -> 4

4

In [33]:
L.reverse()
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [312]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [310]:
np.sort(a)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [313]:
idx = np.argsort(-a)
idx #บอกเป็นตำแหน่ง

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [314]:
a[idx] #เอาตำแหน่งมาลงเป็นค่าใน a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [52]:
np.shape(a)


(10,)

In [51]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
a = a.reshape(1,10)
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [54]:
a = a.reshape(1,10)
np.shape(a)

(1, 10)

In [55]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

-------------------------------------

In [56]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
a[0,0]

1

In [62]:
L =[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

L[0][0]

1

In [65]:
a[1,:] # a[1,0] ถึง a[1,สุดท้าย]

array([4, 5, 6])

In [64]:
a[1]

array([4, 5, 6])

In [63]:
L[1][:]

[4, 5, 6]

In [68]:
a[:,-1] # ได้คอลลัมสุดท้าย

array([3, 6, 9])

-----------------

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
a[:,0]

array([1, 4, 7])

In [72]:
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [74]:
L[:][0] # List ต่างกับ array

[1, 2, 3]

--------------------

In [78]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a[โรล,คอลลัม]

L[โรล][คอลลัม] เพราะเป็นlist

In [79]:
a[:,-2] = 0
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [80]:
a[1,:] = 0
a

array([[1, 0, 3],
       [0, 0, 0],
       [7, 0, 9]])

In [81]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

------------------------

In [82]:
a.shape #ใช้บ่อย

(3, 3)

In [84]:
a.size # 3*3 ใช้บ่อย

9

In [87]:
np.size(a)

9

In [89]:
np.size(a,0) #นับแถว


3

In [88]:
np.size(a,1) #นับคอลลัม

3

In [92]:
a.ndim #หาว่าข้อมูลมีกี่ dim -dimention

2

-----------------------

In [93]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [94]:
np.size(a,1)

3

In [95]:
np.ndim(a)

2

### Data is Matrix.
So, Matrix management == Data Management <br>
rows    = samples <br>
columns = attributes, features

In [96]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

dtype='<U5' คือ ข้อมู,ไม่ใช่เลขแล้ว กลายเป็น object type -> เลขถูกเปลี่ยนเป็น stringอัติโนมัติ

In [98]:
np.array(np_mix_matrix[:,1], dtype = int) #เลข

array([2, 4, 6])

### 2. Special Type of Matrix

In [99]:
a = np.zeros((2,2)) #สร้างเมทริคที่มีแต่เลข 0 
a

array([[0., 0.],
       [0., 0.]])

In [101]:
a = np.zeros((5,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [102]:
b = np.ones((2,2))  #สร้างเมทริคที่มีแต่เลข 1
b

array([[1., 1.],
       [1., 1.]])

In [105]:
b = np.ones((2,2)) * 8
b

array([[8., 8.],
       [8., 8.]])

In [113]:
c = np.full((2,2),8) #สร้างเมทริคที่มีแต่เลข n
c

array([[8, 8],
       [8, 8]])

In [114]:
d = np.eye(2) #เส้นทะแยงมุมเป็น 1
d

array([[1., 0.],
       [0., 1.]])

In [123]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [124]:
c = np.ones((5,5)) * 8
c

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [129]:
c*d # คูณแบบปกติที่ไม่ใช้เมทริก

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [128]:
np.matmul(c,d) # คูณกัน แบบ matic

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [130]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [131]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [137]:
b

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [138]:
np.power(b,2)

array([[64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64.],
       [64., 64., 64., 64., 64.]])

In [132]:

np.empty([5,5])

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [170]:
np.empty((10,10))

array([[4.64416652e-310, 0.00000000e+000, 2.54639495e-313,
        4.94065646e-324, 6.94345195e-310, 5.92878775e-323,
        6.94345550e-310, 2.75859453e-313, 2.42390049e-052,
        0.00000000e+000],
       [1.76170698e-076, 0.00000000e+000, 2.97079411e-313,
        4.94065646e-324, 6.94345195e-310, 5.92878775e-323,
        6.94345550e-310, 3.18299369e-313, 0.00000000e+000,
        0.00000000e+000],
       [6.94345195e-310, 0.00000000e+000, 3.39519327e-313,
        6.94338243e-310, 6.94345152e-310, 6.94345195e-310,
        6.94345550e-310, 3.60739284e-313, 6.94338243e-310,
        0.00000000e+000],
       [6.94345151e-310, 0.00000000e+000, 3.81959242e-313,
        4.94065646e-324, 6.94345152e-310, 5.92878775e-323,
        6.94345550e-310, 4.03179200e-313, 0.00000000e+000,
        0.00000000e+000],
       [1.50690022e-321, 0.00000000e+000, 4.24399158e-313,
        4.94065646e-324, 6.94345152e-310, 5.92878775e-323,
        6.94345550e-310, 4.45619116e-313, 0.00000000e+000,
        0.0

### 3. Random

In [279]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

In [139]:
np.random.rand()

0.5323990044796348

สุ่มเลขตั้งแต่0-1 โดยมีความน่าจะเป็นเท่ากัน

In [176]:
np.random.rand()*10 #สุ่มเลขตั้งแต่0-10 โดยมีความน่าจะเป็นเท่ากัน

9.325573593386588

In [182]:
np.round(np.random.rand()*10) #ปัดเศษ

4.0

In [194]:
np.random.randint(5) #สุ่มเลขตั้งแต่0-4 โดยมีความน่าจะเป็นเท่ากัน โดยค่าเป็นค่าint

4

In [197]:
[np.random.randint(5) for item in range(10)]

[0, 0, 3, 2, 1, 0, 3, 1, 1, 3]

In [236]:
np.random.seed(1) # ทุกครั้งที่สุ่ม จะได้ค่าเหมือนเดิม
np.random.randint(2,5)

3

In [276]:
rng = np.random.RandomState(0)
np_matrix1 = rng.randint(3,size=(5,5))
np_matrix1

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [209]:
np.random.seed(1) # ทุกครั้งที่สุ่ม จะได้ค่าเหมือนเดิม เหมือน seed โลกในเกม
[np.random.randint(2,5) for item in range(10)]

[3, 2, 2, 3, 3, 2, 2, 3, 2, 3]

In [285]:
rng = np.random.RandomState(0)
[rng.randint(2,5) for item in range(10)]

[2, 3, 2, 3, 3, 4, 2, 4, 2, 2]

In [208]:
np.random.rand(5,5) # สุ่ม เมทริก 5*5

array([[0.39676747, 0.53881673, 0.41919451, 0.6852195 , 0.20445225],
       [0.87811744, 0.02738759, 0.67046751, 0.4173048 , 0.55868983],
       [0.14038694, 0.19810149, 0.80074457, 0.96826158, 0.31342418],
       [0.69232262, 0.87638915, 0.89460666, 0.08504421, 0.03905478],
       [0.16983042, 0.8781425 , 0.09834683, 0.42110763, 0.95788953]])

In [211]:
np.round(np.random.rand(5,5)) # มันอยู่ในช่วง0-1

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [1., 0., 1., 1., 1.]])

In [216]:
np.round(np.random.rand(5,5))

array([[1., 1., 1., 1., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 0., 1.],
       [0., 1., 1., 1., 0.]])

In [ ]:
# Ex 1. Please use random to generate this output
# ...

In [213]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5) #สุ่มเลือกมา5อัน

array([2, 4, 1, 9, 7])

In [218]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False) #สุ่มเลือกมา5อัน โดยไม่ซ้ำกัน

array([ 5,  4,  7, 10,  2])

In [303]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.07379201, 0.78695147, 0.06406733, 0.35531036, 0.94183695],
       [0.76459257, 0.46739268, 0.26900105, 0.83169259, 0.55132494],
       [0.07379201, 0.78695147, 0.06406733, 0.35531036, 0.94183695]])

-------------------------------------

In [304]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 1., 1.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 0., 0.]])

In [305]:
idx_choose = np.random.choice(1000,10, replace=False) # สุ่มค่า 0-999 มา 10 ตัว
idx_choose # มีความหมายว่า เลือกมาก 10 ตัว ใน 999 ตำแหน่งของ np_matrix 

array([842, 311, 615, 623, 317, 668, 515, 644, 267, 636])

In [306]:
np_matrix_choose = np_matrix[idx_choose,:] # เลือกตำแหน่งที่สุ่มได้มาแสดงจากทั้งหมด คือ เลือกมา ..
np_matrix_choose

array([[0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 1., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 1., 1., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 1.],
       [0., 0., 0., 0., 1.]])

---------------------

In [ ]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
#
#
#

In [ ]:
import numpy as np

In [101]:
matrix = np.random.rand(10,5) 
matrix[:,-1] = np.round(matrix[:,-1])
matrix


array([[0.52749444, 0.92385838, 0.24886828, 0.14397933, 0.        ],
       [0.33516824, 0.28254983, 0.23537913, 0.2118069 , 1.        ],
       [0.80123928, 0.05496599, 0.99174306, 0.11997947, 0.        ],
       [0.17759596, 0.07038728, 0.95673835, 0.13147605, 1.        ],
       [0.33788662, 0.65786969, 0.06923602, 0.07072323, 0.        ],
       [0.67626861, 0.19300918, 0.24130912, 0.80042546, 1.        ],
       [0.25623568, 0.78345963, 0.58640577, 0.41112737, 0.        ],
       [0.58412458, 0.45404389, 0.95487918, 0.5264947 , 0.        ],
       [0.41220597, 0.14647694, 0.15232637, 0.68014172, 0.        ],
       [0.85174655, 0.74514373, 0.40402169, 0.93588502, 1.        ]])

In [233]:
np_matrix = np.random.randint(11,size = (5,5)) #สุ่ม0-10 ขนาด5*5
np_matrix

array([[10,  1,  6,  5,  2],
       [ 4,  7,  5,  1,  0],
       [ 7,  2,  4, 10,  2],
       [ 3,  2,  5,  2,  5],
       [ 1,  6,  8,  7,  8]])

In [103]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 2, 2, 2, 2],
       [1, 1, 1, 0, 1],
       [2, 0, 1, 0, 2],
       [0, 1, 2, 0, 0],
       [0, 0, 0, 2, 1]])

In [246]:
i,j = np.where(np_matrix == 2) #หาว่าใน np_matrix ไหนมีค่า 2 บ้าง

In [253]:
i

array([0, 0, 1, 3, 4, 4])

In [254]:
j

array([2, 4, 4, 3, 1, 2])

In [252]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range(len(i))]

[(0, 2), (0, 4), (1, 4), (3, 3), (4, 1), (4, 2)]

In [266]:
#Ex 3. Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[idx,:] #arrayเริ่มอ่านจากค่า0 แต่ค่า idxเริ่มจาก1 ทำให้อ่านข้ามตัวแรกไป และ อ่านเกินในตัวสุดท้าย

IndexError: index 5 is out of bounds for axis 0 with size 5

In [110]:
idx = [1,2,3,4,5]
idx = [i-1 for i in idx]
np_matrix[idx,:]

array([[0, 0, 0, 0, 2],
       [0, 2, 0, 0, 1],
       [2, 1, 0, 1, 2],
       [0, 1, 0, 0, 2],
       [0, 2, 0, 1, 2]])

----------------------------------

In [294]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 0, 0, 2, 2],
       [1, 0, 2, 2, 2],
       [0, 0, 1, 1, 1],
       [0, 0, 1, 1, 2],
       [0, 1, 2, 2, 0]])

In [293]:
np_matrix = np.delete(np_matrix,[1,2],0) #โรล1และ2  คือเลข 0 หมายถึงโรล เลข 1 หมายถึงคอลลัม
np_matrix

array([[1, 0, 0, 1, 0],
       [2, 1, 0, 2, 1],
       [2, 1, 0, 1, 1]])

In [295]:
np_matrix = np.delete(np_matrix,[1,2],1) #คอลลัม 1และ 2 คือ เลข 1 หมายถึงคอลลัม
np_matrix

array([[2, 2, 2],
       [1, 2, 2],
       [0, 1, 1],
       [0, 1, 2],
       [0, 2, 0]])

In [299]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[5, 7, 8, 4, 4],
       [7, 7, 4, 9, 0],
       [2, 0, 7, 1, 7],
       [9, 8, 4, 0, 1],
       [9, 8, 2, 3, 1]])

In [300]:
result = (np_matrix == 2)
result

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False]])

In [301]:
np_matrix[result] = 99 #เปลี่ยนเลข result=2 เป็น99
np_matrix

array([[ 5,  7,  8,  4,  4],
       [ 7,  7,  4,  9,  0],
       [99,  0,  7,  1,  7],
       [ 9,  8,  4,  0,  1],
       [ 9,  8, 99,  3,  1]])

In [302]:
np_matrix[np_matrix == 2]=99
np_matrix

array([[ 5,  7,  8,  4,  4],
       [ 7,  7,  4,  9,  0],
       [99,  0,  7,  1,  7],
       [ 9,  8,  4,  0,  1],
       [ 9,  8, 99,  3,  1]])

In [ ]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features.  
# Then, randomly create a label vector for 10 samples.  
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

data_matrix

In [122]:
#matrix = np.random.rand(10,5)
matrix = np.random.randint(10,size=(10,5))
matrix

array([[3, 2, 4, 7, 2],
       [9, 7, 6, 7, 0],
       [9, 4, 6, 0, 0],
       [8, 3, 2, 0, 3],
       [6, 0, 5, 0, 2],
       [7, 2, 3, 7, 7],
       [3, 8, 5, 1, 1],
       [6, 9, 1, 4, 6],
       [4, 0, 6, 0, 6],
       [0, 8, 1, 9, 4]])

label_vector

In [123]:
vector = np.random.randint(2,size=(10))
vector

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [124]:
matrix[vector==0]

array([[3, 2, 4, 7, 2],
       [9, 4, 6, 0, 0],
       [8, 3, 2, 0, 3],
       [6, 0, 5, 0, 2],
       [6, 9, 1, 4, 6],
       [4, 0, 6, 0, 6],
       [0, 8, 1, 9, 4]])

In [125]:
matrix[vector==1]

array([[9, 7, 6, 7, 0],
       [7, 2, 3, 7, 7],
       [3, 8, 5, 1, 1]])

train_data

test_data

In [116]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[5, 2, 4, 3, 4],
       [3, 3, 5, 1, 4],
       [1, 3, 1, 3, 1],
       [3, 1, 2, 2, 4],
       [1, 2, 1, 4, 3]])

### 4. Important Function

In [ ]:
np.max(data)

In [ ]:
np.max(data,0)

In [ ]:
np.max(data,1)

In [ ]:
np.sum(data)

In [ ]:
np.average(data)

In [ ]:
data[0,:]

In [ ]:
np.argmax(data[0,:])

In [ ]:
np.argmin(data[0,:])

In [308]:
np.sort(data[0,:])

NameError: name 'data' is not defined

In [ ]:
np.argsort(data[0,:])

In [ ]:
#Ex.5 How to sort in decreasing order using np.sort
#

In [ ]:
np.arange(1,10,2)

In [ ]:
np.linspace(5,10,10)

In [ ]:
data = np.round(np.random.random((5,5))*3)
data

In [ ]:
data.shape

In [ ]:
data.reshape(1,25)

In [ ]:
tile = [[1,2],
        [3,4]]
tile

In [ ]:
np.tile(tile,(4,1))

In [ ]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

In [ ]:
#

In [ ]:
# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test